name: server_app
description: A server app using the shelf package and Docker.
version: 1.0.0
license: MIT
repository: https://github.com/joechung2008/json-dart
publish_to: none

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  shared_lib:
    path: ../shared_lib
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  coverage: ^1.8.0
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
