name: json_dart_workspace
description: A port of a TypeScript JSON example to Dart.
version: 1.0.0
license: MIT
repository: https://github.com/joechung2008/json-dart
publish_to: none
environment:
  sdk: '>=3.9.0 <4.0.0'
workspace:
  - packages/shared_lib
  - packages/console_app
  - packages/server_app
