name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.9.3'

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install workspace tools
        run: |
          dart pub global activate melos
          dart pub global activate coverage

      - name: Bootstrap workspace
        run: melos bootstrap

      - name: Run workspace tests and produce combined coverage
        run: melos run test:ci

      - name: Upload combined lcov report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: error
